[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"

[workspace.dependencies]
tokio = { version = "1.0" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2"
console-subscriber = "0.4"

[profile.dev]
opt-level = 0

[profile.release]
strip = true
opt-level = 3 # all
lto = true
