export COMPOSE_BAKE := "true"
export RUSTFLAGS := "--cfg tokio_unstable -Awarnings" 


ssl:
  openssl req -x509 -newkey rsa:4096 -keyout tmp/key.pem -out tmp/cert.pem -sha256 -days 365 -nodes -subj "/CN=wallhack"

prep:
  cargo build -p wallhack 
  cargo build -p repl
  cp ../target/debug/{agent,host} ./tmp

dev: prep
  docker compose -f docker-compose.yml stop
  # docker compose -f docker-compose.yml restart agent-server
  docker compose -f docker-compose.yml up