//! Build metadata for version reporting.

// Include build metadata generated by build.rs
pub mod built_info {
	include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Print version information and exit.
pub fn print_version() {
	println!("wallhack {}", built_info::PKG_VERSION);
	println!("Built: {}", built_info::BUILT_TIME_UTC);

	if let Some(commit) = built_info::GIT_COMMIT_HASH {
		println!("Commit: {commit}");
	}

	if built_info::GIT_DIRTY == Some(true) {
		println!("  (dirty working tree)");
	}

	println!("\nFeatures:");
	let features = built_info::FEATURES;
	if features.is_empty() {
		println!("  (none)");
	} else {
		for feature in features {
			println!("  - {feature}");
		}
	}

	println!("\nTarget: {}", built_info::TARGET);
	println!("Profile: {}", built_info::PROFILE);
	println!("Compiler: {}", built_info::RUSTC_VERSION);
}
