//! Build metadata for version reporting.

use std::fmt::Write;

// Include build metadata generated by build.rs
#[allow(clippy::needless_raw_string_hashes, clippy::doc_markdown)]
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Return short version string
#[must_use]
pub fn version_short() -> String {
    format!("{} {}", built_info::PKG_NAME, built_info::PKG_VERSION)
}

/// Return full version information with build metadata.
#[must_use]
pub fn version_verbose() -> String {
    let mut out = version_short();
    let _ = writeln!(out, "Built: {}", built_info::BUILT_TIME_UTC);

    if let Some(commit) = built_info::GIT_COMMIT_HASH {
        let _ = writeln!(out, "Commit: {commit}");
    }

    if built_info::GIT_DIRTY == Some(true) {
        let _ = writeln!(out, "  (dirty)");
    }

    let _ = writeln!(out, "\nFeatures:");
    let features = built_info::FEATURES;
    if features.is_empty() {
        let _ = writeln!(out, "  (none)");
    } else {
        for feature in features {
            let _ = writeln!(out, "  - {feature}");
        }
    }

    let _ = writeln!(out, "\nTarget: {}", built_info::TARGET);
    let _ = writeln!(out, "Profile: {}", built_info::PROFILE);
    let _ = write!(out, "Compiler: {}", built_info::RUSTC_VERSION);
    out
}
