//! Build metadata for version reporting.

// Include build metadata generated by build.rs
#[allow(clippy::needless_raw_string_hashes, clippy::doc_markdown)]
pub mod built_info {
	include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Print short version string and exit (`wallhack <version>`).
pub fn print_version_short() {
	println!("wallhack {}", built_info::PKG_VERSION);
}

/// Print full version information with build metadata.
pub fn print_version_verbose() {
	println!("wallhack {}", built_info::PKG_VERSION);
	println!("Built: {}", built_info::BUILT_TIME_UTC);

	if let Some(commit) = built_info::GIT_COMMIT_HASH {
		println!("Commit: {commit}");
	}

	if built_info::GIT_DIRTY == Some(true) {
		println!("  (dirty working tree)");
	}

	println!("\nFeatures:");
	let features = built_info::FEATURES;
	if features.is_empty() {
		println!("  (none)");
	} else {
		for feature in features {
			println!("  - {feature}");
		}
	}

	println!("\nTarget: {}", built_info::TARGET);
	println!("Profile: {}", built_info::PROFILE);
	println!("Compiler: {}", built_info::RUSTC_VERSION);
}
