[package]
name = "wallhack-api"
version = "0.1.0"
edition = "2024"

[dependencies]
wallhack-core = { path = "../core", default-features = false }
axum = { version = "0.7", default-features = false, features = [
    "tokio",
    "json",
    "http1",
] }
axum-server = { version = "0.7", default-features = false, features = [
    "tls-rustls",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { workspace = true }
tokio-stream = { version = "0.1", features = ["sync"] }
tracing = { workspace = true }
urlencoding = "2"
base64 = "0.22"
subtle = "2"

[lints]
workspace = true
