[package]
name = "wallhackd"
version = "0.2.6"
edition = "2024"

[features]
default = ["quic", "websocket", "http-api"]
slim = ["quic", "websocket"]
tokio-console = ["dep:console-subscriber"]
dns-resolver = ["dep:hickory-resolver"]

# Transport features (forwarded to wallhack-core)
quic = ["wallhack-core/quic"]
websocket = ["wallhack-core/websocket"]

# REST API feature
http-api = ["dep:wallhack-api"]

[dependencies]
hickory-resolver = { version = "0.25", default-features = false, features = [
  "tokio",
], optional = true }
wallhack-wire = { path = "../wire" }
prost = "0.13"
quinn = { version = "0.11", default-features = false, features = [
  "runtime-tokio",
  "rustls-ring",
] }
thiserror = "2"
tokio.workspace = true
tracing.workspace = true
wallhack-core = { path = "../core", default-features = false }
wallhack-api = { path = "../api", optional = true }
console-subscriber = { workspace = true, optional = true }
parking_lot = "0.12.5"
zeroize = "1"

[build-dependencies]
built = { version = "0.7", features = ["git2"] }

[lints]
workspace = true
