[package]
name = "wallhack"
version = "0.1.0"
edition = "2024"
categories = ["network-programming"]

[dependencies]
agent_adapter = { path = "../agent-adapter" }
anyhow = "1.0.98"
dashmap = "6.1.0"
prost = { version = "0.13.5" }
protobuf = { path = "../protobuf" }
quinn = "0.11.7"
rand = "0.9.1"
rcgen = "0.13.2"
rustls = { version = "0.23.26", default-features = false, features = ["ring"] }
rustls-pemfile = "2.2.0"
smoltcp = { version = "0.12", default-features = false, features = [
  "std",
  "alloc",
  "socket-tcp",
  "socket-udp",
  "socket-icmp",
  "medium-ip",
  "medium-ethernet",
  "phy-tuntap_interface",
  "proto-ipv4",
  "proto-ipv6",
] }
socket2.version = "0.5.9"
thiserror = "2.0.12"
tokio.features = ["rt", "macros", "rt-multi-thread", "net", "io-util"]
tokio.workspace = true
tracing.workspace = true
tun = { version = "0.7.21", features = [
  "async",
  "tokio",
], default-features = false }

[build-dependencies]
test-log = { version = "0.2.17", features = ["trace"] }

[dev-dependencies]
test-log = { version = "0.2.17", features = ["trace"] }
tokio-test = "0.4.4"

[lints]
workspace = true
# rust.unsafe_code = "forbid"
